### DISCUSSION TITLE
Using your own reverse proxy | Connecting to http

### DISCUSSION THREAD

**Discussion by TheDenast** [IgnisDa/ryot#1032] [Q&A] [answered]
Hi!

I've been trying to deploy the docker stack to my homelab but I can't seem to access the front-end page using server's wireguard ip & port I specified in docker-compose. I can't seem to access ports 3000 or 5000 either. 

From the docs I see that ryot uses Caddy under the hood, is it not possible to connect to the service directly via http or expose it manually through nginx I have already set up?

**Comment by IgnisDa** [comment]
The exposed port should be 8000. Not sure where you're getting 3000 and 5000 from.

**Reply by TheDenast** [reply]
Sorry if I wasn't clear. I already serve a static webpage on port 8000, so I've been setting the port value in docker-compose to other values (8001, 8282 and so on) but to no success.

My theory was that I couldn't connect directly to the webpage because I've been using wireguard IP + port and reverse proxy packaged with container only allows https connections via domain or something like that. Sorry! I'm not very good with networking and docker.

**Reply by IgnisDa** [reply]
Can you show me your docker compose?

**Reply by TheDenast** [reply]
There:
```
services:
  ryot-db:
    image: postgres:16-alpine # at-least version 15 is required
    restart: unless-stopped
    volumes:
      - /home/denast/Docker/ryot:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=America/New_York
    container_name: ryot-db

  ryot:
    image: ghcr.io/ignisda/ryot:v7 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=America/New_York
    ports:
      - "8282:8282"
    pull_policy: always
    container_name: ryot
```
And here are logs from ryot container:
```
[backend] 2024-09-19T13:11:15.321260Z  INFO ryot: Running version: v7.3.0
[proxy] {"level":"info","ts":1726751475.3445404,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
[proxy] {"level":"warn","ts":1726751475.3457105,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":22}
[proxy] {"level":"warn","ts":1726751475.3459983,"logger":"admin","msg":"admin endpoint disabled"}
[proxy] {"level":"warn","ts":1726751475.3461165,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1726751475.346676,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00037ec00"}
[proxy] {"level":"info","ts":1726751475.3468113,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[proxy] {"level":"info","ts":1726751475.3469534,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
[proxy] {"level":"info","ts":1726751475.3469622,"msg":"serving initial configuration"}
[proxy] {"level":"info","ts":1726751475.347009,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1726751475.3470247,"logger":"tls","msg":"finished cleaning storage units"}
[backend] 2024-09-19T13:11:15.354208Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-09-19T13:11:15.357435Z  INFO sea_orm_migration::migrator: No pending migrations
[backend] 2024-09-19T13:11:15.357718Z  INFO ryot: Timezone: America/New_York
[backend] 2024-09-19T13:11:15.389494Z  INFO ryot: Listening on: 0.0.0.0:5000
[frontend] [remix-serve] http://localhost:3000 (http://192.168.48.2:3000)
```
I run my homelab behind a wireguard connection for administrative actions (for example to set up the service before exposing it with reverse proxy). However, when I try to connect `wireguard_ip:8282` connection fails.

As a note, this approach works for all other containers I run (sonarr, radarr, portainer, you name it). And yes I double checked and port 8282 is not taken on my machine.
