### DISCUSSION TITLE
Local Dockerbuild

### DISCUSSION THREAD

**Discussion by Pr0mises** [IgnisDa/ryot#1410] [Q&A] [answered]
How do I build this project locally? I can't seem to get it working due to this line:
https://github.com/IgnisDa/ryot/blob/c62097c8eea24f7cdc0c6a1136d5d7bc85dc75c6/Dockerfile#L23

Do I need to build it locally as described in https://docs.ryot.io/contributing.html to get the docker working?

**Comment by IgnisDa** [comment, marked as answer]
Yes it needs to be built locally. Please take a look at `.github/workflows/main.yml` for the entire build.

**Reply by Pr0mises** [reply]
Thanks for your quick reply and sorry for replying again even though you closed it.

I was finally able to build it (without cross as I had some openssl1.0 issues) but I noticed this part:
https://github.com/IgnisDa/ryot/blob/main/.github%2Fworkflows%2Fmain.yml#L144-L150

```
      - name: Build
        env:
          UNKEY_API_ID: ${{ secrets.UNKEY_API_ID }}
          APP_VERSION: ${{ steps.build.outputs.version }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          DEFAULT_MAL_CLIENT_ID: ${{ secrets.DEFAULT_MAL_CLIENT_ID }}
          DEFAULT_TMDB_ACCESS_TOKEN: ${{ secrets.DEFAULT_TMDB_ACCESS_TOKEN }}
```

Do I need all of those api keys to get it working or could you please elaborate how the apis are used and what I'm missing without providing it (especially trakt).

Thanks again! Awesome app btw

Edit: I've no trakt and not interested buying/using it at all
