### DISCUSSION TITLE
Not seeing OIDC option

### DISCUSSION THREAD

**Discussion by ikolsteren** [IgnisDa/ryot#756] [Q&A] [answered]
I just started using this tracker and finally got deployed using docker on my Synology NAS
Not sure if I have everything configured correct to begin with.   I don't have a volume mapped for RYOT itself and all my config is in the environment portion of the docker compose.    It has been working and I have my two user setup and everything is maintained after a rebuild etc.   
I added the OIDC portion last night to work with my Authentik server but not seeing the option when I log in

```
  version: "3.9"
  
  services:
    ryot-db:
      image: postgres:16-alpine
      restart: unless-stopped
      volumes:
        - /volume1/docker/ryot/database:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      container_name: ryot-db
  
    ryot:
      image: "ghcr.io/ignisda/ryot:latest"
  #    volumes:
  #      - /volume1/docker/ryot/config:/home/ryot
      environment:
        - DATABASE_URL=postgres://postgres:password@ryot-db:5432/postgres
        - FRONTEND_URL="https://ryot.url"
        - SERVER_OAUTH_CLIENT_ID="IDfromAuthentik"
        - SERVER_OAUTH_CLIENT_SECRET="mysecretfromAuthentik"
        - SERVER_OAUTH_ISSUER_URL="https://authentik.mydomain"
      ports:
        - "7777:8000"
      pull_policy: always
      container_name: ryot
    
  volumes:
    postgres_storage:
```
