### ISSUE TITLE
Ryot Export Failure

### ISSUE THREAD

**Issue by chuanguyen** [IgnisDa/ryot#1070]
After not being able to get exports working on my production RYOT instance, I spun up a test instance with the following docker-compose file. This is fresh with no populated data. Bucket and access key created in the MinIO playground, as per the RYOT export documentation.

```
services:
  ryot-db:
    image: postgres:16-alpine # at-least version 15 is required
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=America/Vancouver
    container_name: ryot-db

  ryot:
    image: ignisda/ryot:v7 # or ghcr.io/ignisda/ryot:v7
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=America/Vancouver
      - FILE_STORAGE_S3_URL=https://play.min.io
      - FILE_STORAGE_S3_BUCKET_NAME=testryotdemo
      - FILE_STORAGE_S3_ACCESS_KEY_ID=wtgpXVwQc3qcFVk7VRuB
      - FILE_STORAGE_S3_SECRET_ACCESS_KEY=un05j7Eo9zBsYoiRAmmx9pyt6YJ8MfvbpwsS6Qre
    ports:
      - "8000:8000"
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:

```

Afterwards, I know S3 access is working, as I can create custom media and be able to upload images. However, when attempting to run an export, I get the following error. 

![Screenshot from 2024-10-14 08-57-48](https://github.com/user-attachments/assets/a771cf60-bb1e-434f-b17b-23662140440a)

What might be wrong here?
