### ISSUE TITLE
docker-compose don't work

### ISSUE THREAD

**Issue by PrzemekSkw** [IgnisDa/ryot#124]
Hello,
I have strange situation. 
I generate docker-compose with https://www.composerize.com/ like that:
![image](https://github.com/IgnisDa/ryot/assets/25219988/c475722b-ac64-45ea-b0a7-7c55423215af)

I start `docker compose up -d` and it looks ok:
```
docker compose up -d
[+] Running 5/5
 ✔ ignisda 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                            3.7s 
   ✔ 012e2d670dc5 Pull complete                                                                                                                                              0.6s 
   ✔ ab1dfc82ca86 Pull complete                                                                                                                                              0.6s 
   ✔ d46e49344c16 Pull complete                                                                                                                                              0.7s 
   ✔ 02054d426ab3 Pull complete                                                                                                                                              2.5s 
[+] Building 0.0s (0/0)                                                                                                                                                           
[+] Running 2/2
 ✔ Network ryot_default  Created                                                                                                                                             0.1s 
 ✔ Container ryot        Started                
 ```
 but with `docker ps` I don't see ryot. It don't work with `http://192.168.0.111:8000`
 
 Regards.

**Comment by dimon222** [comment]
Perhaps you want to mention what did you pass to it otherwise no one will be able to replicate.
Most likely you didn't configure one of required parameters from readme.

**Comment by PrzemekSkw** [comment]
Hi @dimon222 I don't understand what do You mean? "pass to it"?
What paramete? About cookies?

**Comment by IgnisDa** [comment]
What exactly doesn't work?

**Comment by dimon222** [comment]
> Hi @dimon222 I don't understand what do You mean? "pass to it"? What paramete? About cookies?

Pardon, didn't see that you have the exact line in screenshot.
I just repeated all your steps and it works fine (I'm testing on Windows, but I doubt it matters)
Perhaps, try to run with vanilla docker first and see what error it prints?

**Comment by PrzemekSkw** [comment]
@IgnisDa 
```
dietpi@dietpi-laptop:~/ryot$ docker compose up -d
[+] Running 5/5
 ✔ ignisda 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled             3.6s    ✔ ad8a29c0985c Pull complete                               0.6s    ✔ 17738ae7954a Pull complete                               0.6s    ✔ 6563afa447b3 Pull complete                               0.7s    ✔ 522ca21b7d08 Pull complete                               2.5s [+] Building 0.0s (0/0)                                            [+] Running 2/2
 ✔ Network ryot_default  Created                              0.1s  ✔ Container ryot        Started                              0.5s dietpi@dietpi-laptop:~/ryot$ docker ps
CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS       PORTS                                                        NAMES
ca7f1596d79e   frooodle/s-pdf:latest                           "/scripts/init.sh ja…"   3 hours ago    Up 3 hours   0.0.0.0:8066->8080/tcp, :::8066->8080/tcp                                                                                       pdf_stirling-pdf_1
536770367e52   lscr.io/linuxserver/syncthing:latest            "/init"                  2 days ago     Up 2 days    0.0.0.0:8384->8384/tcp, :::8384->8384/tcp, 0.0.0.0:22000->22000/tcp, :::22000->22000/tcp, 0.0.0.0:21027->21027/udp, :::21027->21027/udp, 22000/udp                                                 syncthing
bdb1af019a73   lscr.io/linuxserver/deluge:latest               "/init"                  3 days ago     Up 2 days    0.0.0.0:6881->6881/tcp, :::6881->6881/tcp, 0.0.0.0:8112->8112/tcp, 0.0.0.0:6881->6881/udp, :::8112->8112/tcp, :::6881->6881/udp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp, 0.0.0.0:58846->58846/tcp, :::58846->58846/tcp, 0.0.0.0:58946->58946/tcp, 0.0.0.0:51413->51413/udp, :::58946->58946/tcp, :::51413->51413/udp, 58946/udp   deluge
5cbcfd8763a1   portainer/agent                                 "./agent"                5 days ago     Up 2 days    0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                                                                       portaineragent
8984bf141cf9   nicolargo/glances                               "/bin/sh -c '/venv/b…"   5 days ago     Up 2 days    0.0.0.0:61208-61209->61208-61209/tcp, :::61208-61209->61208-61209/tcp                                                           glances
ac1c92ff374b   ghcr.io/alexjustesen/speedtest-tracker:latest   "/init"                  3 weeks ago    Up 2 days    9000/tcp, 0.0.0.0:8030->80/tcp, :::8030->80/tcp, 0.0.0.0:8453->443/tcp, :::8453->443/tcp                                                                                                           speedtest-tracker
bb68a3356b97   ghcr.io/containrrr/watchtower                   "/watchtower"            4 months ago   Up 2 days    8080/tcp                                                     watchtower
dietpi@dietpi-laptop:~/ryot$ docker compose down
[+] Running 2/2
 ✔ Container ryot        Removed                              0.0s  ✔ Network ryot_default  Removed                              0.1s dietpi@dietpi-laptop:~/ryot$
```

**Comment by PrzemekSkw** [comment]
@dimon222 
I try also docker run:
```
dietpi@dietpi-laptop:~/ryot$ docker run \
> --detach \
> --name ryot \
> --pull always \
>   --publish 8000:8000 \
>   --volume ./ryot/data:/data \
>   --env "WEB_INSECURE_COOKIE=true" \
> ghcr.io/ignisda/ryot:latest
latest: Pulling from ignisda/ryot
Digest: sha256:db3cf5d22128828715f327f307b5401998a1cc2c09ce67fe7588c98e47849ab4
Status: Image is up to date for ghcr.io/ignisda/ryot:latest
818b7384c14ba0bfe6d31a6fb0a5f918ba7134d2b6b61979c3cf7321a32b5978
dietpi@dietpi-laptop:~/ryot$ docker ps
CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS       PORTS                                                        NAMES
ca7f1596d79e   frooodle/s-pdf:latest                           "/scripts/init.sh ja…"   3 hours ago    Up 3 hours   0.0.0.0:8066->8080/tcp, :::8066->8080/tcp                                                                                       pdf_stirling-pdf_1
536770367e52   lscr.io/linuxserver/syncthing:latest            "/init"                  2 days ago     Up 2 days    0.0.0.0:8384->8384/tcp, :::8384->8384/tcp, 0.0.0.0:22000->22000/tcp, :::22000->22000/tcp, 0.0.0.0:21027->21027/udp, :::21027->21027/udp, 22000/udp                                                 syncthing
bdb1af019a73   lscr.io/linuxserver/deluge:latest               "/init"                  3 days ago     Up 2 days    0.0.0.0:6881->6881/tcp, :::6881->6881/tcp, 0.0.0.0:8112->8112/tcp, 0.0.0.0:6881->6881/udp, :::8112->8112/tcp, :::6881->6881/udp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp, 0.0.0.0:58846->58846/tcp, :::58846->58846/tcp, 0.0.0.0:58946->58946/tcp, 0.0.0.0:51413->51413/udp, :::58946->58946/tcp, :::51413->51413/udp, 58946/udp   deluge
5cbcfd8763a1   portainer/agent                                 "./agent"                5 days ago     Up 2 days    0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                                                                       portaineragent
8984bf141cf9   nicolargo/glances                               "/bin/sh -c '/venv/b…"   5 days ago     Up 2 days    0.0.0.0:61208-61209->61208-61209/tcp, :::61208-61209->61208-61209/tcp                                                           glances
ac1c92ff374b   ghcr.io/alexjustesen/speedtest-tracker:latest   "/init"                  3 weeks ago    Up 2 days    9000/tcp, 0.0.0.0:8030->80/tcp, :::8030->80/tcp, 0.0.0.0:8453->443/tcp, :::8453->443/tcp                                                                                                           speedtest-tracker
bb68a3356b97   ghcr.io/containrrr/watchtower                   "/watchtower"            4 months ago   Up 2 days    8080/tcp                                                     watchtower
dietpi@dietpi-laptop:~/ryot$
```
I use DietpiOS (Debian 11) on HP miniPC x64. Never had such problem. Even if Dockers don't work it always been visible with `docker ps` command.

**Comment by dimon222** [comment]
@PrzemekSkw try `docker ps -a` since regular `docker ps` excludes exited containers (these usually exit when they fail). Once u do that, tail/inspect the failed container.

**Comment by PrzemekSkw** [comment]
Hi @dimon222 it shows now:
```
CONTAINER ID   IMAGE                                           COMMAND                  CREATED          STATUS                        PORTS                                                                                                                           NAMES303cb83a0fa9   ghcr.io/ignisda/ryot:latest                     "/app"                   12 seconds ago   Exited (101) 12 seconds ago                                                                ryot
```

**Comment by IgnisDa** [comment]
Are you using windows?

**Comment by PrzemekSkw** [comment]
@IgnisDa Yes it's still exited.

**Comment by IgnisDa** [comment]
Please try with the latest release.

**Comment by PrzemekSkw** [comment]
I pull the last image but still exited. Meybe different port?

**Comment by IgnisDa** [comment]
Use postgres database.

**Comment by PrzemekSkw** [comment]
@IgnisDa don't know how.

**Comment by IgnisDa** [comment]
```yml
version: '3.3'
services:
    ignisda:
        container_name: ryot
        ports:
            - '8000:8000'
        environment:
            - WEB_INSECURE_COOKIE=true
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
        volumes:
            - './ryot/data:/data'
        image: 'ghcr.io/ignisda/ryot:latest'

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_storage:
```

@PrzemekSkw

**Comment by PrzemekSkw** [comment]
Hi, @IgnisDa sorry for late respond. I missed Your previous post.
I have error like that now:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.environment: 'POSTGRES_DB'
```

**Comment by IgnisDa** [comment]
Before running it using docker-compose, you have to create a directory and set correct permissions on it:

```sh
mkdir -p ./ryot
chown -R 1001:1001 ./ryot # might need sudo
```
```yml
version: '3.3'
services:
  ryot:
      container_name: ryot
      ports:
          - '8001:8000'
      environment:
          - WEB_INSECURE_COOKIE=true
          - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      volumes:
          - './ryot:/data'
      image: 'ghcr.io/ignisda/ryot:latest'
      depends_on:
          - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_storage:
```
