### ISSUE TITLE
[Bug] Saved workouts are not visible in 8.2.2

### ISSUE THREAD

**Issue by carbolymer** [IgnisDa/ryot#1262]
Saved workouts are not visible at all in ryot 8.2.2.

## Steps to reproduce
1. Start ryot using this compose file (similar to https://docs.ryot.io/), with an empty database i.e. the postgres volume is not present:
```yaml
services:
  ryot-db:
    image: postgres:17-alpine # at-least version 15 is required
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Amsterdam
    container_name: ryot-db

  ryot:
    image: ghcr.io/ignisda/ryot:v8.2.2
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=Europe/Amsterdam
      - SERVER_ADMIN_ACCESS_TOKEN=28ebb3ae554fa9867ba0
    ports:
      - "8000:8000"
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:
```
2. Open `http://localhost:8000` in a browser
3. Create new user, log in as a new user
4. Go to workouts, start new workout
5. Add two exercises, complete each set.
6. Click on "Finish". Workout took 22 seconds. Summary is displayed.
7. Go to workouts tab

## Expected result

One workout is shown, the one just created.

## Actual results

No workout is created. There are multiple 404 errors in the logs. See: [compose.log](https://github.com/user-attachments/files/18885012/compose.log)
