### ISSUE TITLE
Accessing Ryot from a domain breaks images, sidepanel and settings page

### ISSUE THREAD

**Issue by coolssor** [IgnisDa/ryot#1310]
Hey folks,

Got an interesting one here. When I access Ryot through a domain (e.g. `ryot.domain.tld`), it breaks images (shows just `No Image`), the sidebar (see image where it no longer has submenus) and the Settings page just doesn't exist (returns a 404).

However, when accessing it via an IP address, it works absolutely fine (to test I switched the FRONTEND_URL value in the Compose file since I use OIDC)

For full context:
1. I use a Cloudflare Tunnel to access my Ryot instance pointed to the internal IP address on port 8000
2. I use Authentik OIDC to log into Ryot. This works absolutely fine when using an IP address to access, but shows the error behaviour described above when using a public domain.
3. This is my full Docker Compose file with the sensitive security stuff redacted:

```
services:
  ryot-db:
    image: postgres:16-alpine # at-least version 15 is required
    restart: unless-stopped
    container_name: ryot-db
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - TZ=Europe/London
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ryot:
    image: ignisda/ryot:v8 # or ghcr.io/ignisda/ryot:v8
    pull_policy: always
    container_name: ryot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/London
      - SERVER_ADMIN_ACCESS_TOKEN=<redacted>
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - FRONTEND_URL=https://ryot.domain.tld # The URL of your Ryot instance
      - SERVER_OIDC_CLIENT_ID=<redacted>
      - SERVER_OIDC_CLIENT_SECRET=<redacted>
      - SERVER_OIDC_ISSUER_URL=https://auth.domain.tld/application/o/ryot/
      - SERVER_PRO_KEY=3ZTM48MKggQhGE7QbxBuu6T5
      - USERS_DISABLE_LOCAL_AUTH=true
      - DISABLE_TELEMETRY=true
      - FILE_STORAGE_S3_URL=<redacted>
      - FILE_STORAGE_S3_BUCKET_NAME=<redacted>
      - FILE_STORAGE_S3_ACCESS_KEY_ID=<redacted>
      - FILE_STORAGE_S3_SECRET_ACCESS_KEY=<redacted>

volumes:
  postgres_storage:
```

# Images:
## Accessing from IP address
![Accessing from IP address](https://github.com/user-attachments/assets/bb23704b-622b-4f67-a851-cef10cc99047)
## Accessing from domain
![Image](https://github.com/user-attachments/assets/984ac764-da14-448b-8a58-422df5d51262)
