### ISSUE TITLE
OIDC not working after Authelia update

### ISSUE THREAD

**Issue by iLuckyW** [IgnisDa/ryot#1317]
I just noticed that updating Authelia to version > 4.39 breaks the OIDC integration for me. This is related to this part of the CHANGELOG:

_The default claims for ID Tokens minted by the Authelia OpenID Connect 1.0 Identity Provider have changed._

They provided an article to restore the previous behavior [here](https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter). Adding this from the article fixed the issue I was having:
```
identity_providers:
  oidc:
    claims_policies:
      ## Creates the 'default' claims policy.
      default:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    clients:
      - client_id: 'client_example_id'
        ## Assigns the 'default' claims policy to this client.
        claims_policy: 'default'
```

Not sure if this now requires changes in ryot, if you dont think so, feel free to close this issue. Just putting this out here for others having the same issue.
