### ISSUE TITLE
Requires an external database?

### ISSUE THREAD

**Issue by jack-mil** [IgnisDa/ryot#141]
From what I have gathered from the list of configuration options (database url) and issue #124, this requries an external database server to run. 
I have tried both the Docker quickstart and the compiled binary from releases and am met with a "Database connection failed... Unable to open database file" error. 

I just want to confirm that an external service needs to be running, and `ryot` needs to be configured to connect to it. 

If this is the case and I am not missing something, it would be nice to have the readme and setup examples mention the database requirement, so users trying it out quickly (e.g. with docker) aren't met with an unexpected error immediately

**Comment by IgnisDa** [comment]
I changed the docker commands in `README.md` and added more information about production mode. Feel free to re-open this issue if you have any problems.

**Comment by quamok** [comment]
> I changed the docker commands in `README.md` and added more information about production mode. Feel free to re-open this issue if you have any problems.

may I suggest adding an example for each DB type? I'm trying to find the proper format for the connection string without success. 

Usually, for docker containers, I enter the username, pwd, db port and db ip in different environment variables and it's the 1st time I'm encountering the need for a connection string.

**Comment by IgnisDa** [comment]
Postgres: `postgres://<username>:<password>@<hostname>:<port>/postgres`
SQLite: `sqlite:/data/ryot.db?mode=rwc`
MySQL: `mysql://mysql:8f152407ed8c9f0b@hostname:3306/test`

@quamok

**Comment by nodecentral** [comment]
Hi, I’m still finding my feet in setting up Ryot with a dB, but looking at some of my other container compose files, they seem to break out the db part. Below is a mock up of what I assumed it would look for Ryot ? Is this a viable route too (I’m just missing an environment variable within the idnisda service to connect the two? (If I’m over complicating this let me know :-) )
 
````
version: '3.9'
services:
  ignisda:
    image: 'ghcr.io/ignisda/ryot:latest'
    environment:
        - WEB_INSECURE_COOKIE=true
    ports:
        - '8000:8000'
    volumes:
        - '/share/Container/ryot:/data'
    pull_policy: always
    container_name: ryot
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: ryot-db
    restart: unless-stopped
    volumes:
      - /share/Container/ryotdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ryot
      POSTGRES_USER: ryot
      POSTGRES_PASSWORD: ryot
````
