### ISSUE TITLE
Localization for tmdb

### ISSUE THREAD

**Issue by kenci** [IgnisDa/ryot#154]
Is it possible to add language options for tmdb database, e.g TMDB_LANG=de?

**Comment by IgnisDa** [comment]
Yes, I planned to implement it in https://github.com/IgnisDa/ryot/issues/8, but I thought people might not need it, so ended up not doing it. Will get to this once I get time. It should be easy enough.

**Comment by IgnisDa** [comment]
@kenci Added new configuration parameters to support this! Checkout the updated README.

**Comment by kenci** [comment]
Great news, thank you very much!

**Comment by tiberio87** [comment]
How can I set the tmdb variable for Italian language? My docker compose

```

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SERVER_INSECURE_COOKIE=true # only needed in localhost or non-https
      - TZ=Europe/Rome
      - MOVIES_AND_SHOWS_TMDB_ACCESS_TOKEN=*
    ports:
      - "8100:8000"
    pull_policy: always
    container_name: ryot

```
