### ISSUE TITLE
Bug when Docker directory mounted to /data

### ISSUE THREAD

**Issue by schklom** [IgnisDa/ryot#242]
```yaml
services:
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - SERVER_INSECURE_COOKIE=true
    ports:
      - "8000:8000"
    volumes:
      - ./ryot-data:/data
```
crashes with the log
```
thread 'main' panicked at 'failed to create appender: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-appender-0.2.2/src/rolling.rs:499:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
whereas
```yaml
services:
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - SERVER_INSECURE_COOKIE=true
    ports:
      - "8000:8000"
```
works. Same thing on two different servers.
Did I do something wrong?
