### ISSUE TITLE
[Bug] Importing from Trakt calculates the wrong review score when using "Out Of Five" scale

### ISSUE THREAD

**Issue by bretthysuik** [IgnisDa/ryot#328]
My instance is set up to use the "Out Of Five" scale, but all Trakt reviews were incorrectly imported in the "Out Of Hundred" scale

Example of items imported from Trakt with the wrong scale:
![image](https://github.com/IgnisDa/ryot/assets/2490331/92034538-693a-4168-ba67-1b2c3870637b)

Non-imported items using the "Out Of Five" scale:
![image](https://github.com/IgnisDa/ryot/assets/2490331/b6d9d938-a42a-4a04-9ea5-711e17f2b6b7)

**Comment by IgnisDa** [comment]
what is the expected scale?

**Comment by bretthysuik** [comment]
I expect Trakt reviews to be imported in "Out Of Five" scale since that's what I have configured in the preferences:

![image](https://github.com/IgnisDa/ryot/assets/2490331/b96fd654-f563-4543-8bd3-8df2bce07288)

But they were imported in "Out Of Hundred" scale.

**Comment by IgnisDa** [comment]
Is the review correct if you have selected "out of hundred scale"?

**Comment by bretthysuik** [comment]
> Is the review correct if you have selected "out of hundred scale"?

Had I configured ryot to use "out of hundred" scale prior to the Trakt import, yes the imported ratings would be correct.

> And what is the expected value for the items you have attached in the screenshot?

Expected = imported_rating / 20

So in this screenshot the ratings should have been imported as 1, 4, 0.5, 3, 3 instead of 20, 80, 10, 60, 60
![265897736-92034538-693a-4168-ba67-1b2c3870637b](https://github.com/IgnisDa/ryot/assets/2490331/61ea26a9-5a07-4d95-a3ec-98f73de40f4b)

**Comment by IgnisDa** [comment]
yeah they dont

**Comment by IgnisDa** [comment]
https://github.com/IgnisDa/ryot/blob/170f51cd7c30dad4dd867a2c77147f6df52693c1/apps/backend/src/importer/trakt.rs#L131 the code looks fine to me.

**Comment by IgnisDa** [comment]
Closing due to lack of information.

**Comment by bretthysuik** [comment]
@IgnisDa here are the steps to reproduce:

1. Spin up a new ryot instance via docker. Here's my compose file:

```yml
---
version: '3'

services:
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    container_name: ryot
    restart: unless-stopped
    environment:
      - SERVER_INSECURE_COOKIE=true
      - DATABASE_URL=postgres://ryot:EyTQCogvPddRdTwZ@ryot-db:5432/ryot
      - FRONTEND_ITEM_DETAILS_HEIGHT=650
    ports:
      - 2222:8000
    volumes:
      - /srv/ryot/data:/data

  ryot-db:
    image: postgres:15-alpine
    container_name: ryot-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=EyTQCogvPddRdTwZ
      - POSTGRES_USER=ryot
      - POSTGRES_DB=ryot
    volumes:
      - /srv/ryot-db:/var/lib/postgresql/data
```
2. Go to Settings > Preferences > General and change the rating scale to "Out Of Five"
3. Go to Settings > Imports and Exports and import from Trakt with username `ryot-import`
4. Observe that all 10 imported movies have the wrong rating scale (Out Of Hundred instead of Out Of Five)

![image](https://github.com/IgnisDa/ryot/assets/2490331/4ec7450b-3181-4542-ba4a-321bcfda54d6)

5. Manually add a review for any movie you want and observe that it has the correct rating out of five. Every other movie has the wrong rating scale.

![image](https://github.com/IgnisDa/ryot/assets/2490331/e59727cb-53a9-4e95-9a69-64713eaf2817)
