### ISSUE TITLE
database stopped working out of nowhere

### ISSUE THREAD

**Issue by flintstones-fred** [IgnisDa/ryot#422]
My installation of Ryot has stopped working. Looking at container logs for postgres, this is the error I am getting
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-10-21 16:03:35.055 CDT [1] FATAL:  bogus data in lock file "postmaster.pid": ""
```
Here is the stack I have been using in portainer - 
```
version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - /mnt/USBHDD2/storage/ryot/postgres_data:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_INSECURE_COOKIE=true
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "4567:8000"
    volumes:
      - /mnt/USBHDD2/storage/ryot/ryot_data:/data
    pull_policy: always
    container_name: ryot
    restart: unless-stopped
```
