### ISSUE TITLE
Import via Trakt or manual not working

### ISSUE THREAD

**Issue by StefanBerecz** [IgnisDa/ryot#453]
Corresponding to the request to open a new issue in #450
Trying to add tvshows/movies via trakt import on a fresh install gives these errors:
**ryot-container:**
```
thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:252:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff910f0d681 - <unknown>
   1:     0x7ff90ffbf19c - <unknown>
   2:     0x7ff910f0a21e - <unknown>
   3:     0x7ff910f0d464 - <unknown>
   4:     0x7ff910f14343 - <unknown>
   5:     0x7ff910f1408f - <unknown>
   6:     0x7ff910f14836 - <unknown>
   7:     0x7ff910f14714 - <unknown>
   8:     0x7ff910f13296 - <unknown>
   9:     0x7ff910f144d2 - <unknown>
  10:     0x7ff90fbf8cc3 - <unknown>
  11:     0x7ff90fbf8d53 - <unknown>
  12:     0x7ff910bad5b9 - <unknown>
  13:     0x7ff910ba61b5 - <unknown>
  14:     0x7ff910bcb8c6 - <unknown>
  15:     0x7ff910b88a73 - <unknown>
  16:     0x7ff910c63453 - <unknown>
  17:     0x7ff910c22579 - <unknown>
  18:     0x7ff910aebe81 - <unknown>
  19:     0x7ff910b2b69c - <unknown>
  20:     0x7ff910b146fe - <unknown>
  21:     0x7ff910bee7b4 - <unknown>
  22:     0x7ff91064d022 - <unknown>
  23:     0x7ff910b0f1d3 - <unknown>
  24:     0x7ff910f3e7d9 - <unknown>
  25:     0x7ff910f3e1d0 - <unknown>
  26:     0x7ff910f4e0bf - <unknown>
  27:     0x7ff910f4ffe4 - <unknown>
  28:     0x7ff910f3dbbc - <unknown>
  29:     0x7ff910f5092b - <unknown>
  30:     0x7ff910f46632 - <unknown>
  31:     0x7ff910f44485 - <unknown>
  32:     0x7ff910f5538d - <unknown>
  33:     0x7ff910f3b5ea - <unknown>
  34:     0x7ff910f3ad6c - <unknown>
  35:     0x7ff910f3ac88 - <unknown>
  36:     0x7ff910f3f5b1 - <unknown>
  37:     0x7ff910f52bea - <unknown>
  38:     0x7ff910f4f69d - <unknown>
  39:     0x7ff910f5534e - <unknown>
  40:     0x7ff910f44b70 - <unknown>
  41:     0x7ff910f16f95 - <unknown>
```
Posgresdb (several instances of the same error for different person_id, partial_metadata_id)
```
2023-10-30 01:37:32.194 UTC [751] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
2023-10-30 01:37:32.194 UTC [751] DETAIL:  Key (person_id, partial_metadata_id)=(98, 5614) already exists.
2023-10-30 01:37:32.194 UTC [751] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
2023-10-30 01:38:11.487 UTC [750] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
2023-10-30 01:38:11.487 UTC [750] DETAIL:  Key (person_id, partial_metadata_id)=(108, 6454) already exists.
2023-10-30 01:38:11.487 UTC [750] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
```
Docker-compose would be:
```
version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /path/to/ryot/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespws
      POSTGRES_USER: postgresusr
      POSTGRES_DB: postgresdb
    network_mode: "ryot_default"

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgresusr:postgrespwd@postgresdb:5432/postgres 
      - TZ=redacted
      - PUID=UID
      - PGID=GID
      - VIDEO_GAMES_TWITCH_CLIENT_ID=x
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=x
       - USERS_ALLOW_REGISTRATION=false
      - RUST_BACKTRACE=full
    ports:
      - "8000:8000"
    #volumes:
     # - /path/to/ryot/data:/data
    pull_policy: always
    container_name: ryot
    network_mode: "ryot_default"
```
