### ISSUE TITLE
Can't activate video game

### ISSUE THREAD

**Issue by phrogg** [IgnisDa/ryot#601]
I could enable video games before, but after importing my data and updating the image I cannot enable it any longer. I have IGDB configured and keys in the docker-compose:

```docker-compose
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      [ ... ]
      - video_games.twitch.client_id=XXXXX
      - video_games.twitch.client_secret=XXXXX
```

After enabling it and clicking "Save changes (1)" it just disables itself again. I cannot see anything in the logs related to that.

When I manually go to "videogame" via URL. And search for a game I get this error:
```
ryot     | [frontend] ClientError: invalid type: map, expected a sequence at line 1 column 0: {"response":{"data":null,"errors":[{"message":"invalid type: map, expected a sequence at line 1 column 0","locations":[{"line":2,"column":3}],"path":["mediaSearch"]}],"status":200,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"VIDEO_GAME","input":{"page":1,"query":"bioshock"},"source":"IGDB"}}}
```

**Comment by StoffelCPR** [comment]
You have to define them as Environment variables:

```yaml
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      [ ... ]
      - VIDEO_GAMES_TWITCH_CLIENT_ID=XXXXX
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=XXXXX
   ```
