### ISSUE TITLE
Application error when opening "yours" or "public" collection

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#664]
Hey,

When clicking "yours" or "public" in the collections drop-down, the page goes blank and says Application Error. Nothing appears in the docker logs for this, and here is the relevant `compose.yml`:

```
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=Australia/Perth
      - DISABLE_TELEMETRY=true
      - VIDEO_GAMES_TWITCH_CLIENT_ID=...
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=...
    ports:
      - "8003:8000"
    pull_policy: always
    container_name: ryot
```

Thanks for any help!
