### ISSUE TITLE
Application Error / ECONNREFUSED 127.0.0.1:5000

### ISSUE THREAD

**Issue by Joery** [IgnisDa/ryot#676]
Hi,

Been trying to setup Ryot on my Docker instance but running into the following error:

```
[frontend] [remix-serve] http://localhost:3000 (http://172.16.101.19:3000)
[frontend] GET / 302 - - 24.982 ms
[frontend] FetchError: request to http://localhost:5000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:5000
[frontend]     at ClientRequest.<anonymous> (/home/ryot/node_modules/node-fetch/lib/index.js:1491:11)
[frontend]     at ClientRequest.emit (node:events:514:28)
[frontend]     at Socket.socketErrorListener (node:_http_client:495:9)
[frontend]     at Socket.emit (node:events:514:28)
[frontend]     at emitErrorNT (node:internal/streams/destroy:151:8)
[frontend]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
[frontend]   type: 'system',
[frontend]   errno: 'ECONNREFUSED',
[frontend]   code: 'ECONNREFUSED'
[frontend] }
[frontend] [Error: Unexpected Server Error]
[frontend] GET /auth/login?redirectTo=%2F 500 - - 19.474 ms
```

Docker-compose:
```
services:
  ryot:
    container_name: ryot
    depends_on:
      - postgres
      - traefik
    environment:
      - DATABASE_URL=postgres://user:pass@ryot/ryot
    image: ghcr.io/ignisda/ryot:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.ryot.rule=Host(`ryot.example.com`)
      - traefik.http.services.ryot.loadbalancer.server.port=8000
    networks:
      - backend    # contains postgresql server
      - frontend   # traefik
    restart: unless-stopped
    volumes:
      - docker-data/ryot:/config
```

ryot.yaml
```
frontend:
  url: "https://ryot.example.com"

movies_and_shows:
  tmdb:
    access_token: "xxx"

users:
  jwt_secret: "xxx"
  allow_registration: true
```

There are no errors until I try to access the webpage, where I'm greeted by an "Application Error" and the above is logged. Any idea where it goes wrong?

Thanks!
