### ISSUE TITLE
Can't login or register

### ISSUE THREAD

**Issue by estevez-dev** [IgnisDa/ryot#733]
Using Rayot **4.3.16** I can't log in after creating the initial account. There are no errors in logs and UI.

I tried to clear database files and start from scratch, but it didn't help. Here is my `docker-compose.yaml`:
```
version: "3.9"

services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    user: "1026:100"
    volumes:
      - ./storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:v4.3.16"
    environment:
      - DATABASE_URL=postgres://postgres:password@ryot-db:5432/postgres
      - TZ=Europe/Kyiv
    ports:
      - "8684:8000"
    pull_policy: always
    container_name: ryot
```

After registering I'm getting a login page and trying to log in results in nothing. Here is a log of starting with a clean database and trying to register, then login:
[ryot.csv](https://github.com/IgnisDa/ryot/files/14849995/ryot.csv)
