### ISSUE TITLE
Fresh Docker Setup: Database migration issue

### ISSUE THREAD

**Issue by athiosh** [IgnisDa/ryot#734]
Using docker-compose found on the install page but when received the error below.

```
version: "3.9"

services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
    ports:
      - "8010:8000"
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:
```

`ryot: Database migration failed: Execution Error: error returned from database: column "metadata_group_id" does not exist`
