### ISSUE TITLE
Can't login to new install

### ISSUE THREAD

**Issue by hxck** [IgnisDa/ryot#749]
I've deployed Ryot through Dockge and successfully created a new user, but when I try to login I click the button and nothing happens. My compose file:

```
version: "3.9"
services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-db
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
    ports:
      - 8007:8000
    pull_policy: always
    container_name: ryot
volumes:
  postgres_storage: null
networks:
  backend:
    external: true
```

The logs from Dockge:

```
ryot-db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
ryot-db  | 
ryot-db  | 2024-04-07 16:06:30.534 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
ryot-db  | 2024-04-07 16:06:30.534 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ryot-db  | 2024-04-07 16:06:30.534 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ryot-db  | 2024-04-07 16:06:30.617 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ryot-db  | 2024-04-07 16:06:30.719 UTC [24] LOG:  database system was shut down at 2024-04-07 16:06:26 UTC
ryot-db  | 2024-04-07 16:06:30.744 UTC [25] FATAL:  the database system is starting up
ryot-db  | 2024-04-07 16:06:30.805 UTC [1] LOG:  database system is ready to accept connections
ryot     | [frontend] POST /auth/login?redirectTo=%2F&_data=routes%2Fauth.login 204 - - 101.447 ms
ryot     | [frontend] GET /?_data=routes%2F_dashboard 204 - - 7.482 ms
ryot     | [frontend] GET /?_data=routes%2F_dashboard._index 204 - - 3.616 ms
ryot     | [frontend] GET /?_data=root 200 - - 12.820 ms
ryot     | [frontend] GET /auth/login?redirectTo=%2F&_data=root 200 - - 1.531 ms
ryot     | [frontend] GET /auth/login?redirectTo=%2F&_data=routes%2Fauth.login 200 - - 4.982 ms
```

The URL in my browser shows `http://192.168.50.204:8007/auth/login?redirectTo=%2F`

Not really sure what I'm doing wrong, any help would be appreciated. Thanks!
