### ISSUE TITLE
Have to run the container as root, otherwise it can't access the read only database.

### ISSUE THREAD

**Issue by Sirtz** [IgnisDa/ryot#75]
Basically the title, I made a docker compose to manage the container
```
version: '3.8'

services:
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    pull_policy: always
    container_name: ryot
    volumes:
      - /mnt/500gbcrucial/Ryot/:/data
      - /mnt/500gbcrucial/Ryot/ryot.example.json:/data/config/ryot.json
    ports:
      - 8471:8000
    restart: always
    user: root
```

The problem is that it only works with `user: root` not as normal user. I set permissions of all directories for Ryot to user and 777, but running it after that with a normal user doesn't work and it says it can't write in the read only database, or just errors out with `ryot  | Error: Permission denied (os error 13)`
