### ISSUE TITLE
DB permissions

### ISSUE THREAD

**Issue by Johnymalina** [IgnisDa/ryot#755]
I had my instance working but i moved it to different PC. Now every time i create containers using following compose file it change permissions to ryot folder and i cannot acces my DB anymore i tried somehow to specify user using env variables and also  `user: 1001:1001` without any succes. I tried with old  DB and also delete all and start from scratch. No difference the permissions changed every time i start containers or when theyre running to `drwx------ 19  70 thehorde 4096 Apr  9 22:33 ryot `
```
ryot
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres    
      - TZ=${TZ}      
    ports:
      - "8000:8000"
    pull_policy: always
    container_name: ryot    

  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./config/ryot:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=${TZ}      
    container_name: ryot-db
```
How to continue from here?
