### ISSUE TITLE
[BUG] - OIDC Integration

### ISSUE THREAD

**Issue by jonathanfinley** [IgnisDa/ryot#823]
Good Morning,

I'm testing out ryot and having issues with the intial OIDC setup,  even with the right variables it doesn't seem to be activating the login page. I'm using Authentik as the OIDC Provider.

Thanks in advanced!

```yml
  ryot:
    image: ghcr.io/ignisda/ryot:${RYOT_VERSION:-latest}
    environment:
      DATABASE_URL: postgres://postgres:postgres@ryot-db:5432/postgres
      # - FRONTEND_INSECURE_COOKIES=true # if running on HTTP
      FRONTEND_URL: https://ryot.${DOMAIN}
      SERVER_OIDC_CLIENT_ID: $RYOT_OIDC_CLIENT_ID
      SERVER_OIDC_CLIENT_SECRET: $RYOT_OIDC_CLIENT_SECRET
      SERVER_OIDC_ISSUER_URL: https://auth.${DOMAIN}/application/o/ryot
      SERVER_SMTP_SERVER: $SMTP_HOST
      SERVER_SMTP_PORT: $SMTP_PORT
      SERVER_SMTP_USER: $SMTP_USERNAME
      SERVER_SMTP_PASSWORD: $SMTP_PASSWORD
      SERVER_SMTP_MAILBOX: "RYOT <no-reply@${DOMAIN}>"
      TZ: America/New_York
    container_name: ryot
    labels:
      traefik.enable: true
      traefik.http.routers.ryot.rule: HostHeader(`ryot.${DOMAIN}`)
      traefik.http.routers.ryot.entrypoints: websecure
      traefik.http.routers.ryot.tls.options: securetls@file
      traefik.http.routers.ryot.tls.certresolver: zerossl
      traefik.http.routers.ryot.middlewares: secureHeaders@file
      traefik.http.services.ryot.loadbalancer.server.port: 8000
   ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    restart: unless-stopped
    volumes:
      - /opt/apps/ryot/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
 ```

**Comment by IgnisDa** [comment]
Please upgrade to the latest version. There must be a log appearing which says why the oidc client failed to be created.

**Comment by IgnisDa** [comment]
Try `https://auth.${DOMAIN}/application/o/ryot/` (add trailing slash).

**Comment by jonathanfinley** [comment]
Thanks for the response! here is the error received. I reinstalled it completely fresh just in case.
```
[backend] 2024-05-09T05:01:50.794778Z  INFO ryot: Using timezone: America/New_York
[backend] 2024-05-09T05:01:51.078626Z  WARN ryot::utils: Error while creating OIDC client: Parse(Error { path: Path { segments: [] }, original: Error("missing field `keys`", line: 1, column: 2) })
[backend] 2024-05-09T05:01:51.091906Z  INFO ryot: Instance does not have exercises data. Deploying job to download them...
[backend] 2024-05-09T05:01:51.356625Z  INFO ryot: Listening on: 0.0.0.0:5000
[frontend] [remix-serve] http://localhost:3000 (http://172.19.0.53:3000)
```

**Comment by IgnisDa** [comment]
Can you visit `https://auth.${DOMAIN}/application/o/ryot/.well-known/openid-configuration` in the browser and show me the response? There might be sensitive info, so please redact it if needed.

**Comment by jonathanfinley** [comment]
here you go: 
```
{
  "issuer": "https://auth.${DOMAIN}/application/o/ryot/",
  "authorization_endpoint": "https://auth.${DOMAIN}/application/o/authorize/",
  "token_endpoint": "https://auth.${DOMAIN}/application/o/token/",
  "userinfo_endpoint": "https://auth.${DOMAIN}/application/o/userinfo/",
  "end_session_endpoint": "https://auth.${DOMAIN}/application/o/ryot/end-session/",
  "introspection_endpoint": "https://auth.${DOMAIN}/application/o/introspect/",
  "revocation_endpoint": "https://auth.${DOMAIN}/application/o/revoke/",
  "device_authorization_endpoint": "https://auth.${DOMAIN}/application/o/device/",
  "response_types_supported": [
    "code",
    "id_token",
    "id_token token",
    "code token",
    "code id_token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "jwks_uri": "https://auth.${DOMAIN}/application/o/ryot/jwks/",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported": [
    "HS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
  ],
  "acr_values_supported": [
    "goauthentik.io/providers/oauth2/default"
  ],
  "scopes_supported": [
    "email",
    "openid",
    "profile"
  ],
  "request_parameter_supported": false,
  "claims_supported": [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "acr",
    "amr",
    "nonce",
    "email",
    "email_verified",
    "name",
    "given_name",
    "preferred_username",
    "nickname",
    "groups"
  ],
  "claims_parameter_supported": false,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

**Comment by IgnisDa** [comment]
Did you try setting the env variable with trailing slash?

**Comment by jonathanfinley** [comment]
I did to no avail. That issue seems interesting, but no solve?

Currently running [2024.4.1](https://goauthentik.io/docs/releases/2024.4)

**Comment by IgnisDa** [comment]
Someone had the same problem in #756 but were able to solve it using trailing slash.

**Comment by IgnisDa** [comment]
Closing due to inactivity. Feel free to ping me here if you have any update.

**Comment by jonathanfinley** [comment]
Went out for the weekend, so wasn't near a computer. Did some research in the Authentik Discord today, seems they changed the payload for some of the JWT items. not 100% sure what changed yet.

**Comment by IgnisDa** [comment]
One thing you can do is give me the url to your authentik instance and then i try to connect mine to it.

**Comment by jonathanfinley** [comment]
Okay, so i have a small update, I was able to get the login with OIDC button to show
A. Made sure that the url ended with a hanging `/`
B. Set the Subject mode to be based on the User's email rather the UID.

Now getting a message and random 504 timeouts: 
```
We encountered an error. If you recently upgraded the server, you may have to logout and login again. If the error still persists, please create a new issue on [GitHub](https://github.com/ignisda/ryot/issues).
Logout
```

**Comment by jonathanfinley** [comment]
Okay, refreshed entire install, updated to the latest version. and looks like its now working as expected.

**Comment by Eamourinho** [comment]
Having the same issue, using:
- Authentik 2024.4.2 (latest)
- Latest ryot
- Trailing slash
- Subject mode is set to email rather than UID
- Fresh install

Getting this error:
[backend] 2024-05-31T14:53:14.489874Z  WARN ryot::utils: Error while creating OIDC client: Parse(Error { path: Path { segments: [] }, original: Error("missing field `keys`", line: 1, column: 2) })

https://auth.domain.tld/application/o/ryot/.well-known/openid-configuration contains this:
```
{
  "issuer": "https://auth.domain.tld/application/o/ryot/",
  "authorization_endpoint": "https://auth.domain.tld/application/o/authorize/",
  "token_endpoint": "https://auth.domain.tld/application/o/token/",
  "userinfo_endpoint": "https://auth.domain.tld/application/o/userinfo/",
  "end_session_endpoint": "https://auth.domain.tld/application/o/ryot/end-session/",
  "introspection_endpoint": "https://auth.domain.tld/application/o/introspect/",
  "revocation_endpoint": "https://auth.domain.tld/application/o/revoke/",
  "device_authorization_endpoint": "https://auth.domain.tld/application/o/device/",
  "response_types_supported": [
    "code",
    "id_token",
    "id_token token",
    "code token",
    "code id_token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "jwks_uri": "https://auth.domain.tld/application/o/ryot/jwks/",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported": [
    "HS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
  ],
  "acr_values_supported": [
    "goauthentik.io/providers/oauth2/default"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "profile",
    "offline_access"
  ],
  "request_parameter_supported": false,
  "claims_supported": [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "acr",
    "amr",
    "nonce",
    "email",
    "email_verified",
    "name",
    "given_name",
    "preferred_username",
    "nickname",
    "groups"
  ],
  "claims_parameter_supported": false,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

**Comment by IgnisDa** [comment]
Honestly I don't know how to help you. You seem to have already done all the steps Jonathon did.

Maybe wait for it to magically start working 😜?

**Comment by Eamourinho** [comment]
Maybe @jonathanfinley can think of something else that he did and wasn't mentioned in his posts? 🥲

**Comment by jonathanfinley** [comment]
I migrated my  authentik deployment to terraform, let me see if I can translate.

Authentik:
```
name          = "RYOT"
group         = "Apps"
icon          = "https://raw.githubusercontent.com/IgnisDa/ryot/main/docs/logo.png"
base_url      = "https://ryot.${var.domain}"
launch_url    = "https://ryot.${var.domain}"
redirect_uris = ["https://ryot.${var.domain}/api/auth"]
subject_mode  = "user_email"
```

Docker:
```yaml
services:
  ryot:
    image: ghcr.io/ignisda/ryot:${RYOT_VERSION:-latest}
    container_name: ryot
    environment:
      DATABASE_URL: postgres://postgres:postgres@ryot-db:5432/postgres
      # - FRONTEND_INSECURE_COOKIES=true # if running on HTTP
      FRONTEND_URL: https://ryot.${DOMAIN}
      SERVER_CORS_ORIGINS: https://ryot.${DOMAIN}
      SERVER_OIDC_CLIENT_ID: $RYOT_OIDC_CLIENT_ID
      SERVER_OIDC_CLIENT_SECRET: $RYOT_OIDC_CLIENT_SECRET
      SERVER_OIDC_ISSUER_URL: https://auth.${DOMAIN}/application/o/ryot/
      SERVER_SMTP_SERVER: $SMTP_HOST
      SERVER_SMTP_PORT: $SMTP_PORT
      SERVER_SMTP_USER: $SMTP_USERNAME
      SERVER_SMTP_PASSWORD: $SMTP_PASSWORD
      SERVER_SMTP_MAILBOX: "RYOT <no-reply@${DOMAIN}>"
      TZ: America/New_York

```
