### ISSUE TITLE
[Bug] Add to Watchlist results in HTTP 500 for media 

### ISSUE THREAD

**Issue by Tooa** [IgnisDa/ryot#826]
Hi :wave: ,

## Description

Clicking "Add to Watchlist" for the the Anime "Dr. STONE: STONE WARS" results in a `ClientError: GraphQL Error (Code: 500):` error. 

Let me know if you need further information!

## Steps to reproduce

- Start the application with the provided docker-compose stack
- Navigate to Media -> Anime -> Search
- Enter "Dr. STONE: STONE WARS" in the search bar and select "Anilist"
- Press enter and then click on "Add to Watchlist"

## Expected Behavior

- Anime is added to the Wachtlist

## Actual Behavior

- Error in Log
- Loading spinner on image keeps rotating 
- Anime is not added to Watchlist collection

### Docker-compose Stack

```yaml
---

services:
  ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    restart: unless-stopped
    volumes:
      - ./ryot-db:/var/lib/postgresql/data
    networks:
      - ryot-net
    environment:
      - POSTGRES_PASSWORD=<redacted>
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ryot-db
    
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    container_name: ryot
    restart: unless-stopped
    depends_on:
      - ryot-db
    networks:
      - web
      - ryot-net
    environment:
        - TZ=Europe/Berlin
        - DATABASE_URL=postgres://postgres:<redacted>@ryot-db:5432/ryot-db
        - MOVIES_AND_SHOWS_TMDB_LOCALE=de
        - AUDIO_BOOKS_AUDIBLE_LOCALE=de
        - PODCASTS_ITUNES_LOCALE=de
        - USERS_ALLOW_REGISTRATION=false
        - DISABLE_TELEMETRY=true
    labels:
      - "traefik.enable=true"

      # router
      - "traefik.http.routers.ryot.rule=Host(`ryot.home.arpa`)"
      - "traefik.http.routers.ryot.entrypoints=websecure"
      - "traefik.http.routers.ryot.tls=true"

      # service
      - "traefik.http.routers.ryot.service=ryot"
      - "traefik.http.services.ryot.loadbalancer.server.port=8000"
    
networks:
  ryot-net:
  web:
    external: true
```

### Container Version

```
# [v5.2.7](https://github.com/IgnisDa/ryot/releases/tag/v5.2.7)
$ docker images | grep ryot
ghcr.io/ignisda/ryot                     latest          f4ede1fde3bb   11 hours ago    495MB
```

### Stacktrace

```
ryot     | [frontend] GET /media/search/anime?query=Dr.+STONE%3A+STONE+WARS&_data=root 200 - - 3.319 ms
ryot     | [frontend] GET /media/search/anime?query=Dr.+STONE%3A+STONE+WARS&_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 337.309 ms
ryot     | [backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/providers/anilist/mod.rs:626:56:
ryot     | [backend] called `Option::unwrap()` on a `None` value
ryot     | [frontend] ClientError: GraphQL Error (Code: 500): {"response":{"error":"Service panicked","status":500,"headers":{}},"request":{"query":"mutation CommitMetadata($input: CommitMediaInput!) {\n  commitMetadata(input: $input) {\n    id\n  }\n}","variables":{"input":{"identifier":"113936","lot":"ANIME","source":"ANILIST"}}}}
ryot     | [frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
ryot     | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot     | [frontend]     at file:///home/ryot/build/server/index.js?t=1715302572000:13371:32
ryot     | [frontend]     at action$1 (file:///home/ryot/build/server/index.js?t=1715302572000:13369:3)
ryot     | [frontend]     at Object.callRouteActionRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
ryot     | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot     | [frontend]     at submit (/home/ryot/node_modules/@remix-run/router/router.ts:3156:16)
ryot     | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3091:22)
ryot     | [frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3041:18)
ryot     | [frontend]     at handleResourceRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:296:20) {
ryot     | [frontend]   response: {
ryot     | [frontend]     error: 'Service panicked',
ryot     | [frontend]     status: 500,
ryot     | [frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
ryot     | [frontend]   },
ryot     | [frontend]   request: {
ryot     | [frontend]     query: 'mutation CommitMetadata($input: CommitMediaInput!) {\n' +
ryot     | [frontend]       '  commitMetadata(input: $input) {\n' +
ryot     | [frontend]       '    id\n' +
ryot     | [frontend]       '  }\n' +
ryot     | [frontend]       '}',
ryot     | [frontend]     variables: { input: [Object] }
ryot     | [frontend]   }
ryot     | [frontend] }
```
