### ISSUE TITLE
[BUG] - Cannot login

### ISSUE THREAD

**Issue by saschabrockel** [IgnisDa/ryot#828]
I don't know what happened. The app stopped working for me a while ago and even if I try to reset everything and start with a fresh database I cannot log in. I have appended the logs below. I tried to log in first and then registered which redirected me to log in again but after pressing login, nothing happened.

```
[backend] 2024-05-11T02:01:36.937032Z  INFO ryot: Running version: 5.2.7
[backend] 2024-05-11T02:01:36.963728Z DEBUG sea_orm::driver::sqlx_postgres: 
[backend] DO $$
[backend] BEGIN
[backend]     IF EXISTS (
[backend]         SELECT FROM information_schema.tables
[backend]         WHERE table_name = 'seaql_migrations'
[backend]     ) THEN
[backend]         IF EXISTS (
[backend]             SELECT 1 FROM seaql_migrations
[backend]             WHERE version = 'm20240324_perform_v4_migration'
[backend]         ) THEN
[backend]             IF NOT EXISTS (
[backend]                 SELECT 1 FROM seaql_migrations
[backend]                 WHERE version = 'm20240411_perform_v4_4_3_migration'
[backend]             ) THEN
[backend]                 RAISE EXCEPTION 'Final migration before v5 does not exist, upgrade aborted.';
[backend]             END IF;
[backend] 
[backend]             DELETE FROM seaql_migrations;
[backend]             INSERT INTO seaql_migrations (version, applied_at) VALUES
[backend]                 ('m20230410_create_metadata', 1684693316),
[backend]                 ('m20230413_create_person', 1684693316),
[backend]                 ('m20230417_create_user', 1684693316),
[backend]                 ('m20230419_create_seen', 1684693316),
[backend]                 ('m20230501_create_metadata_group', 1684693316),
[backend]                 ('m20230502_create_genre', 1684693316),
[backend]                 ('m20230504_create_collection', 1684693316),
[backend]                 ('m20230505_create_review', 1684693316),
[backend]                 ('m20230509_create_import_report', 1684693316),
[backend]                 ('m20230622_create_exercise', 1684693316),
[backend]                 ('m20230804_create_user_measurement', 1684693316),
[backend]                 ('m20230819_create_workout', 1684693316),
[backend]                 ('m20230912_create_calendar_event', 1684693316),
[backend]                 ('m20231016_create_collection_to_entity', 1684693316),
[backend]                 ('m20231017_create_user_to_entity', 1684693316),
[backend]                 ('m20231219_create_metadata_relations', 1684693316);
[backend]         END IF;
[backend]     END IF;
[backend] END $$;
[backend]     
[backend] 2024-05-11T02:01:36.968800Z DEBUG sea_orm::database::transaction: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" varchar NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
[backend] 2024-05-11T02:01:36.969539Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-05-11T02:01:36.969583Z DEBUG sea_orm::database::transaction: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" varchar NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
[proxy] {"level":"info","ts":1715392896.9694989,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
[backend] 2024-05-11T02:01:36.969662Z DEBUG sea_orm::database::transaction: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" varchar NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
[backend] 2024-05-11T02:01:36.969848Z DEBUG sea_orm::database::transaction: CREATE TABLE IF NOT EXISTS "seaql_migrations" ( "version" varchar NOT NULL PRIMARY KEY, "applied_at" bigint NOT NULL )
[backend] 2024-05-11T02:01:36.970243Z DEBUG sea_orm::database::transaction: SELECT "version", "applied_at" FROM "seaql_migrations" ORDER BY "version" ASC
[proxy] {"level":"warn","ts":1715392896.9708798,"logger":"admin","msg":"admin endpoint disabled"}
[proxy] {"level":"warn","ts":1715392896.9711142,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1715392896.9717274,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003cc780"}
[backend] 2024-05-11T02:01:36.972382Z  INFO sea_orm_migration::migrator: No pending migrations
[proxy] {"level":"info","ts":1715392896.9735787,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1715392896.9736547,"logger":"tls","msg":"finished cleaning storage units"}
[proxy] {"level":"info","ts":1715392896.9739206,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[proxy] {"level":"info","ts":1715392896.9741473,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
[proxy] {"level":"info","ts":1715392896.9741585,"msg":"serving initial configuration"}
[backend] 2024-05-11T02:01:36.978279Z  INFO ryot: Using timezone: Europe/Berlin
[backend] 2024-05-11T02:01:37.803726Z DEBUG sea_orm::driver::sqlx_postgres: SELECT COUNT(*) AS num_items FROM (SELECT "exercise"."id", "exercise"."identifier", "exercise"."lot", "exercise"."level", "exercise"."force", "exercise"."mechanic", "exercise"."equipment", "exercise"."source", "exercise"."muscles", "exercise"."attributes", "exercise"."created_by_user_id" FROM "exercise") AS "sub_query"
[backend] 2024-05-11T02:01:37.813979Z  INFO ryot: Listening on: 0.0.0.0:5000
[frontend] [remix-serve] http://localhost:3000 (http://172.19.0.70:3000)
[frontend] GET / 302 - - 12.067 ms
[frontend] GET /auth?redirectTo=%2F 200 - - 44.447 ms
[backend] 2024-05-11T02:02:30.466280Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."id", "user"."name", "user"."password", "user"."oidc_issuer_id", "user"."is_demo", "user"."lot", "user"."preferences", "user"."yank_integrations", "user"."sink_integrations", "user"."notifications", "user"."summary" FROM "user" WHERE "user"."name" = 'saschabrockel' LIMIT 1
[backend] 2024-05-11T02:02:30.490550Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."id", "user"."name", "user"."password", "user"."oidc_issuer_id", "user"."is_demo", "user"."lot", "user"."preferences", "user"."yank_integrations", "user"."sink_integrations", "user"."notifications", "user"."summary" FROM "user" WHERE "user"."id" = 1 LIMIT 1
[backend] 2024-05-11T02:02:30.491040Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."preferences" FROM "user" WHERE "user"."id" = 1 LIMIT 1
[frontend] POST /auth?intent=login&_data=routes%2Fauth 204 - - 39.934 ms
[frontend] GET /?_data=root 200 - - 1.777 ms
[frontend] GET /?_data=routes%2F_dashboard 204 - - 1.824 ms
[frontend] GET /?_data=routes%2F_dashboard._index 204 - - 1.369 ms
[frontend] GET /auth?redirectTo=%2F&_data=root 200 - - 2.236 ms
[frontend] GET /auth?redirectTo=%2F&_data=routes%2Fauth 200 - - 5.575 ms
[frontend] GET / 302 - - 2.469 ms
[frontend] GET / 302 - - 4.245 ms
[frontend] GET /auth?defaultForm=register&_data=root 200 - - 1.609 ms
[frontend] GET /auth?defaultForm=register&_data=routes%2Fauth 200 - - 4.425 ms
[backend] 2024-05-11T02:04:34.621125Z DEBUG sea_orm::driver::sqlx_postgres: SELECT COUNT(*) AS num_items FROM (SELECT "user"."id", "user"."name", "user"."password", "user"."oidc_issuer_id", "user"."is_demo", "user"."lot", "user"."preferences", "user"."yank_integrations", "user"."sink_integrations", "user"."notifications", "user"."summary" FROM "user" WHERE "user"."name" = 'saschabrockel') AS "sub_query"
[frontend] POST /auth?intent=register&_data=routes%2Fauth 400 - - 7.917 ms
[frontend] GET /auth?intent=register&_data=root 200 - - 1.437 ms
[frontend] GET /auth?intent=register&_data=routes%2Fauth 200 - - 3.362 ms
[frontend] GET / 302 - - 2.394 ms
[backend] 2024-05-11T02:04:58.514822Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."id", "user"."name", "user"."password", "user"."oidc_issuer_id", "user"."is_demo", "user"."lot", "user"."preferences", "user"."yank_integrations", "user"."sink_integrations", "user"."notifications", "user"."summary" FROM "user" WHERE "user"."name" = 'saschabrockel' LIMIT 1
[backend] 2024-05-11T02:04:58.534648Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."preferences" FROM "user" WHERE "user"."id" = 1 LIMIT 1
[backend] 2024-05-11T02:04:58.534679Z DEBUG sea_orm::driver::sqlx_postgres: SELECT "user"."id", "user"."name", "user"."password", "user"."oidc_issuer_id", "user"."is_demo", "user"."lot", "user"."preferences", "user"."yank_integrations", "user"."sink_integrations", "user"."notifications", "user"."summary" FROM "user" WHERE "user"."id" = 1 LIMIT 1
[frontend] POST /auth?intent=login&_data=routes%2Fauth 204 - - 25.248 ms
[frontend] GET /?_data=routes%2F_dashboard 204 - - 1.716 ms
[frontend] GET /?_data=root 200 - - 0.956 ms
[frontend] GET /?_data=routes%2F_dashboard._index 204 - - 1.413 ms
[frontend] GET /auth?redirectTo=%2F&_data=root 200 - - 1.167 ms
[frontend] GET /auth?redirectTo=%2F&_data=routes%2Fauth 200 - - 5.444 ms
```

My compose file:
```
services:
  ryot:
    container_name: "ryot"
    environment:
      - "SERVER_OIDC_CLIENT_ID=xxx"
      - "TZ=Europe/Berlin"
      - "FRONTEND_URL=http://192.168.178.29:8010"
      - "SERVER_SMTP_USER=info@abc.xyz"
      - "DATABASE_URL=postgres://ryot:xxx@ryot-db:5432/ryot"
      - "SERVER_OIDC_CLIENT_SECRET=xxx"
      - "SERVER_SMTP_SERVER=xxx.xxx.net"
      - "SERVER_SMTP_PORT=587"
      - "SERVER_INSECURE_COOKIE=true"
      - "SERVER_OIDC_ISSUER_URL=https://veri.abc.xyz/application/o/ryot/"
      - "RUST_LOG=ryot=trace,sea_orm=debug"
      - "SERVER_SMTP_PASSWORD=abc"
      - "SERVER_SMTP_MAILBOX=Ryot <info@abc.xyz>"
    image: "ghcr.io/ignisda/ryot:latest"
    networks:
      - "unraid"
    ports:
      - "8010:8000/tcp"
    restart: "unless-stopped"
	
  ryot-db:
    container_name: "ryot-db"
    environment:
      - "TZ=Europe/Berlin"
      - "POSTGRES_PASSWORD=xxx"
      - "POSTGRES_USER=ryot"
      - "POSTGRES_DB=ryot"
    image: "postgres:latest"
    networks:
      - "unraid"
    ports:
      - "5439:5432/tcp"
    volumes:
      - "/mnt/cache/appdata/mediaserver/ryot-db:/var/lib/postgresql/data"
```
